name: ci

on:
  pull_request:
    branches: [main]

jobs:
  Style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"
      
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
     
      - name: Check Go Formatting
        run: test -z $(go fmt ./...)

      - name: Check Linting
        run: staticcheck ./...

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Run All Unit Tests
        run: go test -cover ./...

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run GoSec
        run: gosec ./...